### ISSUE TITLE
[FEATURE] Export Finished TODOS?

### ISSUE THREAD

**Issue by TheCedarPrince** [liyunze-coding/Chat-Task-Tic-Overlay-Infinity#1]
Hi @liyunze-coding ,

What a FANTASTIC tool! I am using it for my [stream](https://www.twitch.tv/thecedarprince) regularly now and me and my chat love it. A quick question I had is would it be possible to create some sort of export function to export current todos to like a csv or text file? I use [todo.txt](https://github.com/todotxt/todo.txt) to track my tasks and would love to be able to bring this into my task tracking workflow more easily (if possible).

Otherwise, no worries! Thanks for making this great tool!

~ tcp :deciduous_tree:

**Comment by liyunze-coding** [comment]
I considered doing that but it doesn't seem possible, to my understanding. It would require a backend such as Lua, Python or Node JS to be achievable. Thanks for the suggestion!
