### ISSUE TITLE
Docs: Update oauth sections of README

### ISSUE THREAD

**Issue by analessthanthree** [liyunze-coding/Chat-Task-Tic-Overlay-Infinity#2]
Hello,

Thanks for this project. My partner used it and was happy with it. I got curious and decided to take a look at the source.

The README sections on migrating from your old task list and on installing fresh instruct you to remove the `oauth:` portion of the token. This conflicts with the correct information in the comment in `auth.js` (which follows *the comments in your tutorial video, as I'm told).

If you'd like, I could update this info myself and submit a PR, to save you the trouble.

Thanks again!

-- Vi

**Comment by liyunze-coding** [comment]
Thank you! Feel free to submit a PR if you'd like ^^

Note that in the latest version, having "oauth:" in the `auth.js` or not will still function as long as the token is valid, as it gets checked in the `index.js`. Thank you!
